# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/plugins/thinking"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/plugins/filesystem"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/plugins/playwright"
    schedule:
      interval: "weekly"
